# CivicBridge AI Deployment Script (PowerShell)

Write-Host "🚀 CivicBridge AI Deployment Script" -ForegroundColor Cyan
Write-Host "====================================" -ForegroundColor Cyan

# Check AWS credentials
Write-Host "`n1. Checking AWS credentials..." -ForegroundColor Yellow
try {
    aws sts get-caller-identity | Out-Null
    Write-Host "✅ AWS credentials found" -ForegroundColor Green
} catch {
    Write-Host "❌ AWS credentials not configured!" -ForegroundColor Red
    Write-Host "Run: aws configure"
    exit 1
}

# Generate and store JWT secret
Write-Host "`n2. Setting up JWT secret in SSM Parameter Store..." -ForegroundColor Yellow
$JWT_SECRET = -join ((65..90) + (97..122) + (48..57) | Get-Random -Count 32 | ForEach-Object {[char]$_})

try {
    aws ssm get-parameter --name "/civicbridge/jwt-secret" --region ap-south-1 2>$null | Out-Null
    Write-Host "⚠️  JWT secret already exists in SSM" -ForegroundColor Yellow
    $response = Read-Host "Do you want to update it? (y/N)"
    if ($response -eq 'y' -or $response -eq 'Y') {
        aws ssm put-parameter --name "/civicbridge/jwt-secret" --value $JWT_SECRET --type "SecureString" --overwrite --region ap-south-1
        Write-Host "✅ JWT secret updated" -ForegroundColor Green
    }
} catch {
    aws ssm put-parameter --name "/civicbridge/jwt-secret" --value $JWT_SECRET --type "SecureString" --region ap-south-1
    Write-Host "✅ JWT secret created" -ForegroundColor Green
}

# Check Bedrock model access
Write-Host "`n3. Checking Bedrock model access..." -ForegroundColor Yellow
Write-Host "⚠️  Please ensure you have enabled these models in AWS Bedrock (us-east-1):" -ForegroundColor Yellow
Write-Host "   - us.amazon.nova-lite-v1:0"
Write-Host "   - us.amazon.nova-pro-v1:0"
Write-Host ""
$response = Read-Host "Have you enabled these models in Bedrock? (y/N)"
if ($response -ne 'y' -and $response -ne 'Y') {
    Write-Host "❌ Please enable Bedrock models first:" -ForegroundColor Red
    Write-Host "   1. Go to: https://console.aws.amazon.com/bedrock/home?region=us-east-1#/modelaccess"
    Write-Host "   2. Click 'Manage model access'"
    Write-Host "   3. Enable 'Amazon Nova Lite' and 'Amazon Nova Pro'"
    Write-Host "   4. Wait for approval (usually instant)"
    exit 1
}

# Build SAM application
Write-Host "`n4. Building SAM application..." -ForegroundColor Yellow
sam build

# Deploy SAM application
Write-Host "`n5. Deploying to AWS..." -ForegroundColor Yellow
sam deploy --guided

# Get API Gateway URL
Write-Host "`n6. Retrieving API Gateway URL..." -ForegroundColor Yellow
$API_URL = aws cloudformation describe-stacks --stack-name civicbridge-ai-mvp --query 'Stacks[0].Outputs[?OutputKey==`ApiBaseUrl`].OutputValue' --output text --region ap-south-1

if ([string]::IsNullOrEmpty($API_URL)) {
    Write-Host "❌ Could not retrieve API URL" -ForegroundColor Red
    exit 1
}

Write-Host "✅ API Gateway URL: $API_URL" -ForegroundColor Green

# Update frontend .env
Write-Host "`n7. Updating frontend configuration..." -ForegroundColor Yellow
@"
# CivicBridge AI Frontend Configuration
# Auto-generated by deploy.ps1

VITE_API_URL=$API_URL
"@ | Out-File -FilePath "frontend/.env" -Encoding UTF8

Write-Host "✅ Frontend .env updated" -ForegroundColor Green

# Summary
Write-Host "`n========================================" -ForegroundColor Green
Write-Host "🎉 Deployment Complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""
Write-Host "API Base URL: " -NoNewline
Write-Host $API_URL -ForegroundColor Green
Write-Host ""
Write-Host "Next Steps:" -ForegroundColor Yellow
Write-Host "1. Test health endpoint: curl $API_URL/health"
Write-Host "2. Start frontend: cd frontend; npm run dev"
Write-Host "3. Register a user via the Register tab"
Write-Host "4. Try Aadhaar lookup with: 111122223333"
Write-Host ""
Write-Host "Important:" -ForegroundColor Yellow
Write-Host "- SNS is in sandbox mode - verify phone numbers in AWS SNS console"
Write-Host "- Monitor CloudWatch Logs for Lambda execution logs"
Write-Host "- Check DynamoDB tables for stored data"
