#!/bin/bash
# CivicBridge AI Deployment Script

set -e

echo "🚀 CivicBridge AI Deployment Script"
echo "===================================="

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check AWS credentials
echo -e "\n${YELLOW}1. Checking AWS credentials...${NC}"
if ! aws sts get-caller-identity > /dev/null 2>&1; then
    echo -e "${RED}❌ AWS credentials not configured!${NC}"
    echo "Run: aws configure"
    exit 1
fi
echo -e "${GREEN}✅ AWS credentials found${NC}"

# Generate and store JWT secret in SSM Parameter Store
echo -e "\n${YELLOW}2. Setting up JWT secret in SSM Parameter Store...${NC}"
JWT_SECRET=$(openssl rand -base64 32 2>/dev/null || python -c "import secrets; print(secrets.token_urlsafe(32))")

if aws ssm get-parameter --name "/civicbridge/jwt-secret" --region ap-south-1 > /dev/null 2>&1; then
    echo -e "${YELLOW}⚠️  JWT secret already exists in SSM${NC}"
    read -p "Do you want to update it? (y/N): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        aws ssm put-parameter \
            --name "/civicbridge/jwt-secret" \
            --value "$JWT_SECRET" \
            --type "SecureString" \
            --overwrite \
            --region ap-south-1
        echo -e "${GREEN}✅ JWT secret updated${NC}"
    fi
else
    aws ssm put-parameter \
        --name "/civicbridge/jwt-secret" \
        --value "$JWT_SECRET" \
        --type "SecureString" \
        --region ap-south-1
    echo -e "${GREEN}✅ JWT secret created${NC}"
fi

# Check Bedrock model access
echo -e "\n${YELLOW}3. Checking Bedrock model access...${NC}"
echo -e "${CYAN}ℹ️  AWS Bedrock models are now auto-enabled on first use!${NC}"
echo "   Models will be activated automatically when your Lambda functions invoke them."
echo ""
echo "   Note: For Anthropic models, first-time users may need to submit use case details."
echo "   Amazon Nova models (used in this project) are instantly available."
echo ""
echo -e "${GREEN}✅ No manual model activation needed - proceeding with deployment!${NC}"

# Build SAM application
echo -e "\n${YELLOW}4. Building SAM application...${NC}"
sam build

# Deploy SAM application
echo -e "\n${YELLOW}5. Deploying to AWS...${NC}"
sam deploy --guided

# Get API Gateway URL
echo -e "\n${YELLOW}6. Retrieving API Gateway URL...${NC}"
API_URL=$(aws cloudformation describe-stacks \
    --stack-name civicbridge-ai-mvp \
    --query 'Stacks[0].Outputs[?OutputKey==`ApiBaseUrl`].OutputValue' \
    --output text \
    --region ap-south-1)

if [ -z "$API_URL" ]; then
    echo -e "${RED}❌ Could not retrieve API URL${NC}"
    exit 1
fi

echo -e "${GREEN}✅ API Gateway URL: $API_URL${NC}"

# Update frontend .env
echo -e "\n${YELLOW}7. Updating frontend configuration...${NC}"
cat > frontend/.env << EOF
# CivicBridge AI Frontend Configuration
# Auto-generated by deploy.sh

VITE_API_URL=$API_URL
EOF

echo -e "${GREEN}✅ Frontend .env updated${NC}"

# Summary
echo -e "\n${GREEN}========================================${NC}"
echo -e "${GREEN}🎉 Deployment Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo -e "API Base URL: ${GREEN}$API_URL${NC}"
echo ""
echo -e "${YELLOW}Next Steps:${NC}"
echo "1. Test health endpoint: curl $API_URL/health"
echo "2. Start frontend: cd frontend && npm run dev"
echo "3. Register a user via the Register tab"
echo "4. Try Aadhaar lookup with: 111122223333"
echo ""
echo -e "${YELLOW}Important:${NC}"
echo "- SNS is in sandbox mode - verify phone numbers in AWS SNS console"
echo "- Monitor CloudWatch Logs for Lambda execution logs"
echo "- Check DynamoDB tables for stored data"
